name: Playground - Action Matrix

on:
  workflow_dispatch:

jobs:
  mother:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        A: [A1, A2, A3, A4]
        B: [B1, B2, B3, B4]
        C: [C1, C2, C3, C4]
        D: [D1, D2, D3, D4]

    steps:
     - run: echo ${{ matrix.A }} ${{ matrix.B }} ${{ matrix.C }} ${{ matrix.D }}
