name: Playground - Just SSH
run-name: SSH [${{ inputs.backend }}, BG ${{ inputs.background }}]

on:
  workflow_dispatch:
    inputs:
      backend:
        type: choice
        required: false
        description: '选择后端'
        default: 'ngrok'
        options:
          - ngrok
          - n2n
          - tmate
      background:
        type: boolean
        description: '后台运行'
        default: false

jobs:
  SSH:
    runs-on: ubuntu-latest
    env:
      IN_BACKGROUND: ${{ inputs.background }}
    steps:
    - name: File Descriptors
      run: |
        sudo ls -la /proc/$$/fd/

    - name: Start SSH via ngrok
      id: ngrok
      if: inputs.backend == 'ngrok'
      uses: 1-1-2/SSH2Actions@main
      with:
        mode: ngrok
      env:
        # jp, ap, us
        NGROK_REGION: jp
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Start n2n
      id: n2n
      if: inputs.backend == 'n2n'
      uses: 1-1-2/SSH2Actions@main
      with:
        mode: n2n
      env:
        N2N_ARG: ${{ secrets.N2N_ARG }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Start SSH via tmate
      id: tmate
      if: inputs.backend == 'tmate'
      uses: 1-1-2/SSH2Actions@main
      with:
        mode: tmate

    - run: cat /tmp/conn.inf
      if: steps.ngrok.conclusion == 'success' || steps.ngrok.conclusion == 'success'

    - name: bg Keepalive
      if: inputs.background == true
      run: |
        elapse() {
          if [[ -e "/tmp/continue" ]]; then
              echo -e "[INFO] Continue to the next step."
              exit 0
          fi
          echo "[INFO] $1 online, 'touch /tmp/continue' to continue."
          sleep 5
        }

        while [[ -S /tmp/tmate.sock ]]; do
            elapse Tmate
        done

        while [[ -n $(pgrep ngrok) ]]; do
            elapse Ngrok-ssh
        done

        while [[ -n $(pgrep edge) ]]; do
            elapse 'N2N-edge'
        done

    - uses: GitRML/delete-workflow-runs@main
      if: ${{ always() }}
