name: SSH

on:
  workflow_dispatch:
    
env:
  REPO_URL: https://github.com/openwrt/openwrt

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: list file descriptors
      run: |
        sudo ls -la /proc/$$/fd/
    - uses: mxschmitt/action-tmate@v3

    - uses: GitRML/delete-workflow-runs@main
      if: ${{ always() }}
