name: Test - Action Context

on:
  workflow_dispatch:
  push:
    paths:
      - '**Action Context.yml'

jobs:
  a-job:
    runs-on: ubuntu-latest
    steps:
      - name: Context - gitHub
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Context - job
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Context - steps
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Context - runner
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Context - strategy
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Context - matrix
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: VM Info
        run: |
          echo 'Show who is logged on and what they are doing.'
          echo '===============w==============='
          w
          echo '==============EOF=============='
          echo
          echo 'Print real and effective user and group IDs'
          echo '============== id=============='
          id
          echo '==============EOF=============='
          echo
          echo '==========/etc/passwd=========='
          cat /etc/passwd
          echo '==============EOF=============='
          echo
          echo '========== /etc/group=========='
          cat /etc/group
          echo '==============EOF=============='
          echo
          echo '=========ENV variables========='
          export -p
          echo '==============EOF=============='

          echo '========= Archive Home========='
          du $HOME -akd1 | sort -n | awk '$1 < 10240' | cut -f 2- | tar -cf home_$USER.tar -T -
          echo "USER=$USER" >> $GITHUB_ENV
          echo "TGZ_FILE=$PWD/home_$USER.tar" >> $GITHUB_ENV
          echo '==============EOF=============='
          echo "TimeStamp=$(date +"%Y%m%d-%H%M")" >> $GITHUB_ENV

      - name: Upload User Home Dir
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.USER }}_home_dir
          path: ${{ env.TGZ_FILE }}
